### ISSUE TITLE
Checkout is not disabled when "Unable to determine the taxing jurisdictions."

### ISSUE THREAD

**Issue by vovarudakov94** [classyllama/ClassyLlama_AvaTax#125]
Checkout is not disabled when the error "Unable to determine the taxing jurisdictions." received.

### Preconditions
1. Magento 2.1.9
2. PHP 7.0.28
3. MySQL 5.7.21-20

### Steps to reproduce
1. Go to admin panel: Stores->Configuration->Sales->Tax->Avatax Settings->Error handling Settings->Error action and set it to "Disable checkout & show error message"
Here are full settings:
https://www.awesomescreenshot.com/image/3322957/bdbaf2156af20a52fba2cffbec526a4d
2. Place an order using this shipping address:
159 fearer rd ext
Friendsville, California, 21531
United States

### Expected result
1. Checkout is disabled due to an error: "Unable to determine the taxing jurisdictions."

### Actual result
1. Order is placed
Looks like it happens because AvaTax does send a tax amount field 0.
Here are logs:
https://www.awesomescreenshot.com/image/3320782/8a0a62d53ed60378a67b47c8ce314868

**Comment by rsisco** [comment]
@vovarudakov94 - I've confirmed that the referenced configuration setting doesn't always stop checkout. I've opened an internal ticket to address this issue.

**Comment by rsisco** [comment]
@vovarudakov94 I just reviewed your screenshots again and looked deeper into my own reproduction of the issue and found the following:

- The log screenshot that you provided does not correspond with the address you provided. It also doesn't appear to be from the checkout step, since the destination address is [empty except for state and zip](http://take.ms/Junou), this is likely from the cart page.
- With the address you provided, AvaTax will likely not return an error. It will use the zip code to determine the taxable jurisdiction. Do have a log file you can provide that shows a request that results in "Unable to determine taxing jurisdictions."? The only way I can produce that error is with a completely fake zip code (e.g. 12345), and I am stopped from proceeding to checkout with the expected modal.

**Comment by rsisco** [comment]
@vovarudakov94 Are you able to provide me with the information I had previously requested?
