### ISSUE TITLE
Add support for TaxIncluded API flag

### ISSUE THREAD

**Issue by erikhansen** [classyllama/ClassyLlama_AvaTax#127]
1. Setting the __STORES > Settings > Configuration > SALES > Tax > Calculation Settings > Catalog Prices = Including Tax__ will cause the AvaTax extension to set ‘TaxIncluded = true’ for the products in the API call
2. Setting the __STORES > Settings > Configuration > SALES > Tax > Calculation Settings > Shipping Prices = Including Tax__ will cause the AvaTax extension to set ‘TaxIncluded = true’ for shipping in the API call
3. When the AvaTax extension assigns the values to the product, it will also assign the appropriate pre and post tax values for the items on the order.

These changes are only to affect how the AvaTax extension communicates with the Avalara system for tax calculation in order to accommodate your desire to set the products' price attribute to include sales tax in the set value.

**Comment by rsisco** [comment]
There are a few things items worth noting when using this functionality:

1. An individual product's subtotal may display inaccurately in the cart:
![](http://take.ms/vDMVN)
As noted in the screenshot, this is the result of rounding when the pretax price is being calculated from the provided post-tax price and tax rate. This same behavior is encountered when using native Magento tax calculation in this scenario and is not related specifically to the AvaTax extension.
2. When prices include tax, applied discount amounts are considered to include tax:
![](http://take.ms/ovWtf)
This behavior should account for most use cases, since a discount will typically need to reduce the taxable amount of the order (exceptions being reimbursable discounts like manufacturer's coupons where the merchant ultimately still receives the full order value).
3. When prices exclude tax, applied discount amounts are considered to exclude tax:
![](http://take.ms/Ylfd2)

**Comment by erikhansen** [comment]
@rsisco What's the status of this functionality? Did it ever get released?

**Comment by rsisco** [comment]
@erikhansen This is still pending verification by the merchant.

**Comment by erikhansen** [comment]
@Avalara - See the latest comment on the PR linked to above for the details on the status of this issue.

**Comment by erikhansen** [comment]
This issue will be addressed once the new maintainers of this extension merge in the code from the #228 PR. Closing this ticket since all future development will be done in this repo: https://github.com/avadev/Avalara-AvaTax-for-Magento2
