### ISSUE TITLE
setup:di:compile Error using composer

### ISSUE THREAD

**Issue by mdclark01** [classyllama/ClassyLlama_AvaTax#13]
When installing this extension via the commands below:

composer require classyllama/module-avatax:dev-master
bin/magento module:enable --clear-static-content ClassyLlama_AvaTax 
bin/magento setup:upgrade 
bin/magento cache:flush

then running bin/magento setup:di:compile I get the following error message "[ErrorException] ltrim() expects parameter 1 to be string, array given".

If I delete the extension via composer then I can recompile again no issues. Other extension work fine.

**Comment by mschlanser** [comment]
I'm seeing this as well.  Any help would be awesome!

**Comment by erikhansen** [comment]
@mdclark01 and @mschlanser Magento's [documentation](http://devdocs.magento.com/guides/v2.0/config-guide/cli/config-cli-subcommands-compiler.html#config-cli-subcommands-single) about compilation says:

_There is a known issue with the single-tenant compiler; it does not currently compile proxies. Therefore, if you're preparing to deploy to production, you must use the multi-tenant compiler._

I was able to reproduce the issue you described using `bin/magento setup:di:compile`, however since it is known to be broken, you should use `bin/magento setup:di:compile-multi-tenant` as that works just fine.

Please re-open this issue if you run into problems with compiling using `bin/magento setup:di:compile-multi-tenant`

**Comment by erikhansen** [comment]
FYI, @SamTay submitted a pull request to Magento to fix the `ltrim` issue you both reported: https://github.com/magento/magento2/pull/4081

**Comment by erikhansen** [comment]
@mdclark01 @mschlanser The "ltrim" issue with DI compilation has been fixed in the latest release: https://github.com/classyllama/ClassyLlama_AvaTax/releases You should be able to use `bin/magento setup:di:compile` without any problem now.
