### ISSUE TITLE
setup:di:compile error using manual install of AvaTax module

### ISSUE THREAD

**Issue by inspiredchu** [classyllama/ClassyLlama_AvaTax#2]
When this line as per your documentation:

composer require avalara/avatax:14.4.4

it installs the avalara/avatax module in the magneto/vendor folder. When you run:

php bin/magento setup:di:compile, you get the following error:

[Magento\Framework\Exception\FileSystemException]                                     
  Invalid path: /var/www/html/magento/app/code/ClassyLlama/AvaTax/../../avalara/avatax  

I solved this by moving the files from the magento/vendor folder to the magento/app/code folder.

Hope this helps someone in the future.

**Comment by erikhansen** [comment]
I never ran into this issue when testing. If anyone else is able to reproduce this issue, I'll take another look and try to reproduce it.

**Comment by erikhansen** [comment]
@inspiredchu Do you get this issue if you run the compiler in multi tenant mode?

**Comment by inspiredchu** [comment]
I didn't test it compiling in multi tenant mode, but I believe that the source of the error comes from the ClassyLlama_AvaTax/registration.php file. In it, you register both modules... ClassyLlama_AvaTax and avalara/avatax:
`
<?php

\Magento\Framework\Component\ComponentRegistrar::register(
    \Magento\Framework\Component\ComponentRegistrar::MODULE,
    'ClassyLlama_AvaTax',
    __DIR__
);

\Magento\Framework\Component\ComponentRegistrar::register(
    \Magento\Framework\Component\ComponentRegistrar::LIBRARY,
    'Avalara_AvaTax',
    __DIR__ . DIRECTORY_SEPARATOR . '..' . DIRECTORY_SEPARATOR . '..' . DIRECTORY_SEPARATOR . 'avalara' . DIRECTORY_SEPARATOR . 'avatax'
);
`
I believe the problem occurs when the modules are in different module folders (app/code vs vendor). If the user installs both modules using composer, then both will be in the /vendor folder. I believe the issue will only pop up if the user uses composer to install one module and then manually installs another module in the app/code folder.

**Comment by erikhansen** [comment]
@inspiredchu Oh, that makes sense. I'll add this to our backlog to fix.

**Comment by hiephm** [comment]
@erikhansen Not sure why do you need to add Avalara_AvaTax to registration.php? I think it is autoloaded by PSR-4 already (same way as monolog or braintree)

**Comment by erikhansen** [comment]
@hiephm Good point. I'll test to see if I can remove that next time I work on this extension.

**Comment by davidalger** [comment]
The file should simply look like this…

```php
<?php

use \Magento\Framework\Component\ComponentRegistrar;

ComponentRegistrar::register(ComponentRegistrar::MODULE, 'ClassyLlama_AvaTax',  __DIR__);
```

It's kind a the point of using the magic constant ;)

**Comment by SamTay** [comment]
@davidalger That is what the file usually looks like, but it is perfectly fine to register more than one module in a ``registration.php`` file (the fact that the registration file exists is what gives you flexibility in defining and specifying the location of the module). For instance I am developing a "conglomerate module" that has a single registration.php, but registers five submodules in ``__DIR__ . DIRECTORY_SEPARATOR . 'ModuleName'``.

However, I would say there is an issue with the current avatax ``registration.php``, because it is assuming a /vendor directory structure.

**Comment by lindyk** [comment]
With the latest version 1.2.0, I still have an issue when I try to do bin/magento  setup:di:compile
[Magento\Framework\Exception\FileSystemException]                    
  Invalid path: /Users/lindy/sites/project/vendor/avalara/avatax  

When I tried to manually create avalara/avatax directory under vendor, it passes that state and give different exception:
>  [ReflectionException]                               
  Class AvaTax\ValidateRequestFactory does not exist 
>  [ReflectionException]                               
  Class AvaTax\ValidateRequestFactory does not exist
>  [RuntimeException]                                                                                     
  Source class "\AvaTax\ValidateRequest" for "AvaTax\ValidateRequestFactory" generation does not exist. 

I am running in developer mode and PHP 7.0.22

Because of this failure, when I tried to go to checkout/cart page, I got an error 
3 exception(s):
Exception #0 (ReflectionException): Class ClassyLlama\AvaTax\Framework\Interaction\TaxCalculation\Proxy does not exist
Exception #1 (ReflectionException): Class ClassyLlama\AvaTax\Framework\Interaction\TaxCalculation\Proxy does not exist
Exception #2 (RuntimeException): Class AvaTax\GetTaxResult does not exist

**Comment by erikhansen** [comment]
@lindyk We've had a number of people report these types of issues, and it's typically related to not exactly following the installation instructions. Can you follow the instructions [here](https://www.classyllama.com/documentation/extensions/avatax-magento-2-module#installation), and if you still have an issue, open a new Github issue? Thanks.
