### ISSUE TITLE
Restocking Fee Causing Unbalance errors/Warning Banner Can't be Disabled

### ISSUE THREAD

**Issue by joshuaqueenava** [classyllama/ClassyLlama_AvaTax#226]
{*}Account Name:{*} ------
{*}Account Number(s):{*} -----
{*}Company Code(s):{*} -----
{*}AvaTax Environment:{*} ------ 
{*}ERP Version:{*} Magento 2.1.7 Enterprise 
{*}AvaTax Integration Version:{*} AvaTax 1.4.9 
{*}AvaTax Adapter Version:{*} 15.5.1.0 
{*}OS/Browser Version:{*} Chrome	
{*}Repro Frequency{*} 

{*}Description:{*} 
Many orders came over as Unbalanced. We suspect this has to do with a restocking fee that is charged for returns, etc. Please review account and determine if unbalanced errors can be prevented.

Also a warning banner related to AvaTax cannot be turned off. Customer would like option to remove banner instead of seeing it permanently.

{*}Steps to Reproduce:{*} 
Create invoice with restocking fee, review AvaTax log for unbalanced error.

{*}Expected Result:{*} 
Restocking fee charged and proper tax calculated by AvaTax.

Warning banner option to remove warning.

{*}Actual Result:{*} 
Many transactions showing as Unbalanced
 {*}Attachments/Documentation:{*}
Will upload video and audit logs/reports

**Comment by joshuaqueenava** [comment]
[ModaAuditLog_and_Report.zip](https://github.com/classyllama/ClassyLlama_AvaTax/files/2774114/ModaAuditLog_and_Report.zip)

**Comment by joshuaqueenava** [comment]
https://avalara1-my.sharepoint.com/:v:/g/personal/joshua_queen_avalara_com/EVNUteituC9Crj6aSPJcoakBc-6kI9HbD0O_szROZh9HOg?e=e65AXf

**Comment by joshuaqueenava** [comment]
@prestonchoate  are there any updates on this ticket?

**Comment by prestonchoate** [comment]
@joshuaqueenava This one is projected to be started the week of Feb 11. If you feel it needs to be prioritized please let me know.

**Comment by joshuaqueenava** [comment]
@prestonchoate if you could, please give this highest priority. I believe customer is contacting Magento due to response times on this issue. They are taking this very seriously.

**Comment by prestonchoate** [comment]
@joshuaqueenava For the notification issue there is a config setting to turn off that notification altogether if the client wishes to not see it. Stores -> Config -> Sales -> Tax -> Avatax Settings -> Enable Queue Failure Notification. Setting that to No will disable the AvaTax Queue Failure notification completely. I am still investigating the unbalanced thing to determine if there is some further setting or what needs to be done exactly.

**Comment by prestonchoate** [comment]
@joshuaqueenava The unbalanced notification in the queue is definitely from the adjustment made to the credit memo total. It is there simply to notify you that the total amount of tax that is shown on the credit memo in Magento does not match the total amount that is shown in AvaTax. That is because by default Magento does not recalculate the amount of tax to refund on a credit memo after you have entered an adjustment to the credit memo total. So if you were to run a report on the amount of tax refunded Magento would show the pre-adjustment values for tax while AvaTax would show the post adjustment amount. Modifying the stock Magento Credit Memo behavior for this seems like it would not be worth the time required to invest in it. Does that adjusting how that works is critical?

**Comment by joshuaqueenava** [comment]
@prestonchoate Do you have a status update on this ticket? Is it being worked, also do you have a recording of our meeting from 2/8?

**Comment by erikhansen** [comment]
Avalara has shifted how they are handling support for this extension and are no longer providing support via Github issues. If you are still experiencing this issue, please contact support@avalara.com
