### ISSUE TITLE
Error when refunding to store credit

### ISSUE THREAD

**Issue by andrelundsett** [classyllama/ClassyLlama_AvaTax#47]
We sometimes create credit memos for orders paid with credit card, with the refund going to store credit. In this case the tax is successfully reported to Avatax, but the extension gets into trouble when updating the order after talking to Avatax, and we see this message in the queue:

`"Record was sent to AvaTax, but error occurred after sending record: Could not save credit memo PREVIOUS ERROR: You can't use more store credit than the order amount.”`

This seems like a bug, as it should be a legitimate use case to refund to store credit even if the order was not paid with store credit.

See screenshots:

![image](https://cloud.githubusercontent.com/assets/4931990/21721533/1311db42-d429-11e6-8512-1439f3f7f0c7.png)

![image](https://cloud.githubusercontent.com/assets/4931990/21721560/2275d8ae-d429-11e6-8d41-038e9a2d39af.png)

**Comment by erikhansen** [comment]
@andrelundsett I wanted to let you know that we are working on this issue. Unfortunately in order to solve this issue, we're having to rework how we're saving some data on invoices and credit memos, so it's taking a while to resolve. I don't have an ETA for you, but a fix _is_ in the works. 

In the meantime, if you need a workaround, let me know and we can provide a patch.

**Comment by erikhansen** [comment]
@andrelundsett I know it's been several months since you reported this issue, but we've finally refactored the module to avoid this situation from occurring. I just merged the fix (https://github.com/classyllama/ClassyLlama_AvaTax/commit/4e77d0b38df88aa9bbd48e0e8dc816a70d832e7d) into develop and am wondering whether you'd be willing to test it to confirm that your issues goes away when using code from the develop branch?

**Comment by Jazzercise** [comment]
The fix works perfectly in my testing! 

I noticed 'avatax_is_unbalanced' and 'base_avatax_tax_amount' have been moved out from sales_invoice/sales_creditmemo tables to the new tables avatax_sales_invoice/avatax_sales_creditmemo. Was that done in this fix? We have a couple of custom reports which use those attributes, so I'll need to make sure I coordinate updates to those reports to when we deploy the avatax update to production.

**Comment by erikhansen** [comment]
@Jazzercise Glad this works for you! Yes, those columns have been moved into their own tables. See the 0.4.0 release notes here for details on what has changed: https://github.com/classyllama/ClassyLlama_AvaTax/blob/develop/CHANGELOG.md

**Comment by erikhansen** [comment]
@Jazzercise We just updated the documentation to cover how "unbalanced" information is being stored: https://www.classyllama.com/documentation/extensions/avatax-magento-2-module#avatax-queue-unbalanced Let me know if you have any questions.

Also, I officially tagged a [0.4.0 release](https://github.com/classyllama/ClassyLlama_AvaTax/releases/tag/0.4.0), so closing this task.
