### ISSUE TITLE
When Freeshipping is applied AvaTax still calculates Tax

### ISSUE THREAD

**Issue by rameshpushparaj** [classyllama/ClassyLlama_AvaTax#52]
We have cart price rules set to allow free shipping on orders with subtotal above $40.  It appears that AvaTax calculates Tax for the free shipping promo.

I am using 
magento version 2.0.10
avatax version   0.3.1

**Comment by erikhansen** [comment]
@rameshpushparaj This issue may be fixed in the latest version of the extension. Can you try to upgrade to the latest version and see if your issue is resolved? By the way, version 0.3.0 and beyond of this extension dropped official support for Magento 2.0.x.

**Comment by rameshpushparaj** [comment]
erikhansen, but unfortunately the magento upgrade is not going to happen at our client side for atleast 1 month. But the site is in Live now. Is there any way we can apply some patch code to avatax version 0.3.1 without upgrading magento.

**Comment by erikhansen** [comment]
@rameshpushparaj It sounds like you're already using AvaTax 0.3.1 which doesn't officially support Magento 2.0.x. So if you've been able to use 0.3.1 successfully then you should be able to upgrade to 0.3.4 without issue. Can you try upgrading and let me know what happens?

**Comment by erikhansen** [comment]
@rameshpushparaj Were you able to test this on 0.3.4?

**Comment by rameshpushparaj** [comment]
@erikhansen  How to upgrade AvaTax 0.3.4 version alone without upgrading magento?  Can i upgrade AvaTax without manually downloading the latest version and upload it in server.  Please help

**Comment by erikhansen** [comment]
@rameshpushparaj What method of installing AvaTax are you using? Composer or manually copying files into `app/code/ClassyLlama/AvaTax`?

While you can use 0.3.4 and later versions on Magento 2.0.x, it is not recommended. In release 0.3.0, we removed a workaround for a 2.0.x bug: https://github.com/classyllama/ClassyLlama_AvaTax/commit/f4f2416f53634635f8509aa92135045249d86795 Since that workaround is no longer in place after version 0.3.0, you may experience erratic behavior in the checkout page, especially on slow internet connections. However, if you need to install a newer version of this extension (anything after 0.3.0) on Magento 2.0.x, you can create a patch that reverts the change made in commit [f4f2416](https://github.com/classyllama/ClassyLlama_AvaTax/commit/f4f2416f53634635f8509aa92135045249d86795) and apply the patch using [composer-patches](https://github.com/cweagans/composer-patches).

**Comment by rameshpushparaj** [comment]
I realized that tax is calculated for items in cart and as well as for shipping cost. When the free shipping is applied tax will not be calculated for shipping cost, but tax will still be applicable for items in cart.  For Free Shipping with 100%discount (Tax returns 0). Hence closing this issue.
