### ISSUE TITLE
Tax results for some jurisdictions result in an error when placing an order

### ISSUE THREAD

**Issue by rsisco** [classyllama/ClassyLlama_AvaTax#81]
**Steps to reproduce:**
1. In the merchant's Avalara account, add Washington state as a taxable jurisdiction
2. As a customer, attempt to place a taxable order with a shipping address that includes a City, State, Zip of: Puyallup, WA 98371-5904

**Expected behavior:**
1. The order will be placed successfully.

**Actual behavior:**
1. An error occurs and the order is not placed.
Error as displayed to the customer:
![img](http://take.ms/W59xb)
The actual exception that occurs is similar to:
Integrity constraint violation: 1062 Duplicate entry 'xxx-xxxx' for key 'SALES_ORDER_TAX_ITEM_TAX_ID_ITEM_ID'

**Identified Cause:**
The issue occurs when a jurisdiction has multiple tax codes that incorrectly evaluate as equal with the == operator (e.g. '53' and '053').

**Comment by rsisco** [comment]
Since the comparison operation in question occurs in the Magento source, we will avoid the false positive by prepending a string to the jurisdiction code before it leaves the AvaTax extension.

**Comment by erikhansen** [comment]
@rsisco Make sure to include explicit details about this in your changelog. Since the tax codes show in native Magento tax reports, this could be considered a non backwards compatible change, so we should increment the module version number from 1.1.4 to 1.2.0.

Example of where the tax codes show in the admin (REPORTS > Sales > Tax):

![magento admin-wbeam](https://user-images.githubusercontent.com/129031/30704963-cd8a2bae-9eb9-11e7-80ce-ed0d965079b2.png)

**Comment by rsisco** [comment]
This has been fixed as of version [1.2.0](https://github.com/classyllama/ClassyLlama_AvaTax/releases/tag/1.2.0).
